name: SamIam
favicon: null
layout_spectrum: 1
typography_spectrum: 0.33551
title: SamIam
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3d3d3'
    - '#848484'
    - '#439e8f'
    - '#3ec9b1'
    - '#15190a'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
