name: SamIam
favicon: null
layout_spectrum: 1
typography_spectrum: 0.61489
title: SamIam
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c5722d'
    - '#fefefd'
    - '#611c09'
    - '#e9b164'
  brandStrength: 1
  lightness: 0.21552345086820424
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
