name: SamIam
favicon: null
layout_spectrum: 1
typography_spectrum: 0.33551
title: SamIam
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8e0cb'
    - '#08254f'
    - '#86275c'
    - '#8b7985'
    - '#b1aa9a'
  brandStrength: 0.9375
  lightness: 0.3125
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
