name: SamIam
favicon: null
layout_spectrum: 1
typography_spectrum: 0.61489
title: SamIam
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030303'
    - '#afafaf'
    - '#5e5e5e'
    - '#e64529'
  brandStrength: 1
  lightness: 0.21552345086820424
  saturation: 0.36573497019708157
  rhythmicContrast: 0.9101950542535633
purpose: []
