name: SamIam
favicon: null
layout_spectrum: 1
typography_spectrum: 0.33551
title: SamIam
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060e20'
    - '#194c79'
    - '#392845'
    - '#103768'
    - '#704687'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
